# -*- coding: utf-8 -*-
"""E-Commerce .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MMbNF2TsrmX1YJAyOOT4eM12ZHpq16ZU

# Import Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv("Superstore.csv")

# View data
df.head()

"""# Dataset Information"""

df.info()

df.describe()

df.shape

"""# Check Missing Values"""

df.isnull().sum()

"""# Remove Duplicates"""

df.drop_duplicates(inplace=True)
print("Duplicates removed")

"""# Convert Date Columns"""

df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

"""# Save Cleaned Dataset"""

df.to_csv("cleaned_superstore.csv", index=False)